### ISSUE TITLE
Error messages in login and register endpoints

### ISSUE THREAD

**Issue by Kalela** [paulrimiru/e-commerse#4]
The error messages for validation and other auth errors are inconsistent. Using the pattern below would be beneficial for consuming the responses
```
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "user does not have the required roles",
    "errorCode":"4011"
}
```
Suggest using an incremental value for the error code. 401{1}, 401{2}, 401{n} for 401s and 400{1}, 400{2}, 400{n} for 400s.

**Comment by paulrimiru** [comment]
I was thinking of our earlier discussion and I think we should use a format like this
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "property": "email",
            "children": [],
            "constraints": {
                "isEmail": "email must be an email"
            }
        },
        {
            "property": "password",
            "children": [],
            "constraints": {
                "minLength": "password too short"
            }
        }
    ]
}
```

This way we can validate multiple fields at the same time and get their respective errors. I think we can have the app check the type of message object before processing it instead.

**Comment by Kalela** [comment]
Makes sense. I'll see how I can check the message objects then use the responses.

**Comment by paulrimiru** [comment]
Okay, so i modified the error messages to have the above, you ac test then close this issue

**Comment by Kalela** [comment]
Closing cause the issue is solved.
