### ISSUE TITLE
Need an endpoint for changes user roles/ register admin roles

### ISSUE THREAD

**Issue by Kalela** [paulrimiru/e-commerse#8]
I'm attempting to add products but my token does not have the sufficient privileges' to add products due to role restriction.

**Comment by paulrimiru** [comment]
Have you verified your account?

**Comment by paulrimiru** [comment]
An email should be sent to your email, check your spam if you cant find it.

**Comment by Kalela** [comment]
I've been using your account for the endpoints. Let me try and use mine

**Comment by paulrimiru** [comment]
This is already fixed
